### ISSUE TITLE
Option to open rsub files in a separate window

### ISSUE THREAD

**Issue by aristidesfl** [henrikpersson/rsub#41]
If there is no open window when an incoming connection is received, rsub already creates a one.
This is a request for an option which makes rsub open files always in a separate window.
Ideally rsub would assign a window to itself, and open all files in that window.

**Comment by randy3k** [comment]
I have submitted two PRs, one to [rmate](https://github.com/aurora/rmate), another #42.  
With these two PRs, one to do `rmate -n foo.txt`.

**Comment by aristidesfl** [comment]
Nice, what about an option in rsub so you don't have to specify -n all the time?

**Comment by randy3k** [comment]
note that the `-n` options will always open a new window, it is a little bit different from what you expect (i.e., open all files in the same new windows).

if you really want to open echo files in a different new window, you can make an alias `rmate` to `rmate -n`.

**Comment by aristidesfl** [comment]
I guess that is also a valid way of doing it :)

If your pull request gets merged, let's still leave this open for the option to make all rsub files open in a dedicated window.

**Comment by davidolrik** [comment]
@aristidesfl You could use the perl version of [rmate](https://github.com/davidolrik/rmate-perl), it's mostly the same but defaults to opening files in new windows.

**Comment by aristidesfl** [comment]
@davidolrik even without modifications to rsub like the ones in @randy3k pull request?

**Comment by randy3k** [comment]
My pr to rub has been merged.

**Comment by davidolrik** [comment]
@aristidesfl No, those changes are needed but they have been merged so everything is awesome!

**Comment by KES777** [comment]
Why ticket is not closed yet if resolved?
