### ISSUE TITLE
rsub isn't installing properly

### ISSUE THREAD

**Issue by vdemchenko3** [henrikpersson/rsub#59]
I'm having a bit of issues getting this to work.  I don't have superuser privileges on my remote machine so I did ~/rsub instead of /usr/local/bin, but this didn't work.  When I type rsub filename.py after ssh-ing into my remote machine, I get error "-bash: rsub: command not found".  My .ssh/config has the remote forwarding lines added to it.  Any idea what I've done wrong?

**Comment by Drarok** [comment]
Late reply I know; I was only added to the repo recently, but it may help other people with the same issue…

You either need to put the `rsub` tool in a path that's in your `$PATH` environment variable, or use `~/rsub filename.py` to run it.

**Comment by aspenlin** [comment]
Any idea why rsub is in my $PATH but still not recognized?

The output of my echo $PATH is 

/opt/nvidia/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin

and 'which rsub' gives:

/usr/local/bin/rsub

I have to type 'sudo /usr/local/bin/rsub **.txt' to get the local Sublime text to open the file on remote server

**Comment by KES777** [comment]
@aspenlin because of access rights. Check `ls -l /usr/local/bin/ | grep rsub`
For example I put my `rsub` into `/home/user/bin`

**Comment by aspenlin** [comment]
But I already used sudo in my command, should this solve the access rights issue? 
I don't have a /home/user/bin directory. 

'sudo rsub -f filename' gives error:
sudo: rsub: command not found

'sudo /usr/local/bin/rsub -f filename' works for me.

Sorry if I sound silly. New to linux.

**Comment by KES777** [comment]
1. **What is the result of next command?** `$ ls -l /usr/local/bin/ | grep rsub` 
2. **su** user have different `$PATH`. Compare: `$ sudo env | grep PATH` and `$ env | grep PATH`
3. Also what is the result of command: `echo $(which rsub) && rsub`
